roids:
  version: 0.4.0
app:
  message: "Test from YAML"
  somenumber: 69
  somearray:
  - "this is a test"
  - "this is a another test"
  - "here is another"
  complextype:
    somenumber2: 12.4
    otherarray:
    - 123
    - 456
    - 987
