name: Go
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get . && go get github.com/stretchr/testify/assert
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./...
