name: Publish Go Package
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    paths:
      - 'version.yaml'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v4

      - name: Get the version
        id: get-version
        run: echo "::set-output name=version::$(grep 'version' version.yaml | awk -F':' '{print $2}' | tr -d ' ')"

      - name: Create a tag
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.ROID_PAT }}
          script: |
            const version = "${{ steps.get-version.outputs.version }}"
            const tag_name = `v${version}`
            const tag_message = `Release ${tag_name}`
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag_name}`,
              sha: context.sha
            })
